package net.sourceforge.opencamera.webserver;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Generated by claude.ai
 *
 * Fast median-cut (MMCQ-style) color quantizer.
 *
 * Guarantees:
 *  - result.palette.length <= maxColors  (never exceeds it, by construction)
 *  - every palette entry is used by at least one pixel (no dead slots)
 *  - if the image has fewer unique quantized colors than maxColors, you simply
 *    get fewer colors back — that's correct behavior, not a bug.
 *
 * Why it's faster than Wu here:
 *  - Wu's classic algorithm always scans/evaluates the *entire* histogram cube
 *    (e.g. 33^3 bins) during its variance-minimizing box search, regardless of
 *    how many unique colors the image actually has.
 *  - This implementation only ever operates on the list of *non-empty* buckets,
 *    which for most real images is far smaller than the full cube, and the
 *    split step is a simple sort + weighted-median cut (no variance/moment math).
 *
 * Complexity: O(pixels) for the histogram pass + O(k log k) for splitting,
 * where k = number of populated buckets (<< pixels for most images).
 */
public final class FastMedianCutQuantizer {

    /** Bits kept per channel. 6 -> 64 levels/channel -> 262144 buckets. Lower = faster, less accurate. */
    private static final int SIGBITS = 6;
    private static final int RSHIFT = 8 - SIGBITS;
    private static final int BUCKETS_PER_AXIS = 1 << SIGBITS;
    private static final int TOTAL_BUCKETS = BUCKETS_PER_AXIS * BUCKETS_PER_AXIS * BUCKETS_PER_AXIS;

    public static final class Result {
        public final int[] palette;       // ARGB, length <= maxColors, fully opaque
        public final int[] pixelIndices;  // same length as input pixels, index into palette

        Result(int[] palette, int[] pixelIndices) {
            this.palette = palette;
            this.pixelIndices = pixelIndices;
        }
    }

    // One populated histogram bucket
    private static final class Bucket {
        final int r, g, b;      // quantized bucket coords (0..BUCKETS_PER_AXIS-1)
        final long count;       // pixel count in this bucket
        final long sumR, sumG, sumB; // for weighted average color

        Bucket(int r, int g, int b, long count, long sumR, long sumG, long sumB) {
            this.r = r; this.g = g; this.b = b;
            this.count = count;
            this.sumR = sumR; this.sumG = sumG; this.sumB = sumB;
        }
    }

    // A box = contiguous range [lo, hi) into the sorted 'buckets' list, plus cached bounds
    private static final class Box {
        int lo, hi; // half-open range into buckets list
        int rMin, rMax, gMin, gMax, bMin, bMax;
        long count;

        Box(List<Bucket> buckets, int lo, int hi) {
            this.lo = lo; this.hi = hi;
            recompute(buckets);
        }

        void recompute(List<Bucket> buckets) {
            rMin = gMin = bMin = Integer.MAX_VALUE;
            rMax = gMax = bMax = Integer.MIN_VALUE;
            count = 0;
            for (int i = lo; i < hi; i++) {
                Bucket bk = buckets.get(i);
                if (bk.r < rMin) rMin = bk.r; if (bk.r > rMax) rMax = bk.r;
                if (bk.g < gMin) gMin = bk.g; if (bk.g > gMax) gMax = bk.g;
                if (bk.b < bMin) bMin = bk.b; if (bk.b > bMax) bMax = bk.b;
                count += bk.count;
            }
        }

        int longestAxis() {
            int rr = rMax - rMin, gr = gMax - gMin, br = bMax - bMin;
            if (rr >= gr && rr >= br) return 0;
            if (gr >= rr && gr >= br) return 1;
            return 2;
        }
    }

    private FastMedianCutQuantizer() {}

    /**
     * @param pixels    ARGB pixel array, e.g. from Bitmap.getPixels(...)
     * @param maxColors requested palette size upper bound (must be >= 1)
     */
    public static Result quantize(int[] pixels, int maxColors) {
        if (maxColors < 1) throw new IllegalArgumentException("maxColors must be >= 1");

        // --- Pass 1: build histogram, and remember each pixel's bucket index for reuse later ---
        long[] count = new long[TOTAL_BUCKETS];
        long[] sumR = new long[TOTAL_BUCKETS];
        long[] sumG = new long[TOTAL_BUCKETS];
        long[] sumB = new long[TOTAL_BUCKETS];
        int[] pixelBucket = new int[pixels.length];

        for (int i = 0; i < pixels.length; i++) {
            int p = pixels[i];
            int r = (p >> 16) & 0xFF, g = (p >> 8) & 0xFF, b = p & 0xFF;
            int rq = r >> RSHIFT, gq = g >> RSHIFT, bq = b >> RSHIFT;
            int idx = (rq << (2 * SIGBITS)) | (gq << SIGBITS) | bq;
            pixelBucket[i] = idx;
            count[idx]++;
            sumR[idx] += r; sumG[idx] += g; sumB[idx] += b;
        }

        // --- Collect populated buckets ---
        List<Bucket> buckets = new ArrayList<>();
        // map from raw bucket index -> position in 'buckets' list, filled in after sort
        int[] bucketPos = new int[TOTAL_BUCKETS];
        Arrays.fill(bucketPos, -1);

        for (int idx = 0; idx < TOTAL_BUCKETS; idx++) {
            if (count[idx] == 0) continue;
            int rq = (idx >> (2 * SIGBITS)) & (BUCKETS_PER_AXIS - 1);
            int gq = (idx >> SIGBITS) & (BUCKETS_PER_AXIS - 1);
            int bq = idx & (BUCKETS_PER_AXIS - 1);
            buckets.add(new Bucket(rq, gq, bq, count[idx], sumR[idx], sumG[idx], sumB[idx]));
        }

        // Edge case: fewer unique colors than requested -> just return them all, 1:1
        if (buckets.size() <= maxColors) {
            int[] palette = new int[buckets.size()];
            for (int i = 0; i < buckets.size(); i++) {
                Bucket bk = buckets.get(i);
                palette[i] = averageColor(bk);
                bucketPos[(bk.r << (2 * SIGBITS)) | (bk.g << SIGBITS) | bk.b] = i;
            }
            int[] indices = new int[pixels.length];
            for (int i = 0; i < pixels.length; i++) indices[i] = bucketPos[pixelBucket[i]];
            return new Result(palette, indices);
        }

        // --- Median-cut split until we have maxColors boxes ---
        List<Box> boxes = new ArrayList<>();
        boxes.add(new Box(buckets, 0, buckets.size()));

        while (boxes.size() < maxColors) {
            // pick the box with the largest pixel count to split (population method)
            int splitIdx = -1;
            long best = -1;
            for (int i = 0; i < boxes.size(); i++) {
                Box bx = boxes.get(i);
                if (bx.hi - bx.lo <= 1) continue; // can't split a single bucket further
                if (bx.count > best) { best = bx.count; splitIdx = i; }
            }
            if (splitIdx < 0) break; // nothing left to split -> fewer unique colors than maxColors

            Box bx = boxes.get(splitIdx);
            final int axis = bx.longestAxis();
            // sort only this box's range by the chosen axis
            List<Bucket> sub = buckets.subList(bx.lo, bx.hi);
            sub.sort((a, c) -> axis == 0 ? Integer.compare(a.r, c.r)
                    : axis == 1 ? Integer.compare(a.g, c.g)
                    : Integer.compare(a.b, c.b));

            // weighted-median split point (balances pixel count, not bucket count)
            long half = bx.count / 2, running = 0;
            int mid = bx.lo;
            for (int i = bx.lo; i < bx.hi; i++) {
                running += buckets.get(i).count;
                mid = i + 1;
                if (running >= half) break;
            }
            if (mid == bx.lo) mid = bx.lo + 1;          // avoid empty box
            if (mid == bx.hi) mid = bx.hi - 1;

            Box left = new Box(buckets, bx.lo, mid);
            Box right = new Box(buckets, mid, bx.hi);
            boxes.set(splitIdx, left);
            boxes.add(right);
        }

        // --- Build final palette + bucket->paletteIndex map ---
        int[] palette = new int[boxes.size()];
        for (int i = 0; i < boxes.size(); i++) {
            Box bx = boxes.get(i);
            long sr = 0, sg = 0, sb = 0, c = 0;
            for (int j = bx.lo; j < bx.hi; j++) {
                Bucket bk = buckets.get(j);
                sr += bk.sumR; sg += bk.sumG; sb += bk.sumB; c += bk.count;
                bucketPos[(bk.r << (2 * SIGBITS)) | (bk.g << SIGBITS) | bk.b] = i;
            }
            palette[i] = 0xFF000000 | ((int) (sr / c) << 16) | ((int) (sg / c) << 8) | (int) (sb / c);
        }

        // --- Pass 2: map every pixel to its final palette index (pure array lookups, no recompute) ---
        int[] indices = new int[pixels.length];
        for (int i = 0; i < pixels.length; i++) {
            indices[i] = bucketPos[pixelBucket[i]];
        }

        return new Result(palette, indices);
    }

    private static int averageColor(Bucket bk) {
        return 0xFF000000 | ((int) (bk.sumR / bk.count) << 16)
                | ((int) (bk.sumG / bk.count) << 8)
                | (int) (bk.sumB / bk.count);
    }
}